Repository Team-Ji-s/ReactShop, pull requests merged in 2022-07, with the labels that each got.

#2 Design: carousel button 사이즈 수정
  src/components/carousel/Carousel.jsx
  yarn.lock
Labels: Design

#1 Lina css
  package-lock.json
  package.json
  postcss.config.js
  src/components/Alert.jsx
  src/components/Badge.jsx
  src/components/BreadCrumbs.jsx
  src/components/CartModal.jsx
  src/components/Confirm.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/ProductModal.jsx
  src/components/Search.jsx
  src/components/card/CardItem.jsx
  src/components/card/CardList.jsx
  src/components/card/CardSection.jsx
  src/data/footerData.js
  src/hook/Filter.jsx
  src/index.css
  src/utils/theme.js
  src/views/Accessory.jsx
  src/views/Cart.jsx
  src/views/Digital.jsx
  src/views/Fashion.jsx
  src/views/MainPage.jsx
  src/views/ProductPage.jsx
  tailwind.config.js
  yarn.lock
Labels: Design

#3 Design : tailwind, daisyui 적용
  src/components/Header.jsx
  src/components/Search.jsx
  src/components/StarRate.jsx
  src/components/card/CardList.jsx
  src/views/ProductPage.jsx
Labels: Design

#4 Search 반응형 + 뱃지 컴포넌트 코드 수정
  src/components/Badge.jsx
  src/components/Header.jsx
  src/components/Search.jsx
  src/utils/theme.js
  src/views/ProductPage.jsx
Labels: Design, Refactor

#5 Design : 카트 리스트 반응형 추가
  src/views/Cart.jsx
Labels: Design

#6 Chore : autoprefixer 패키지 설치
  package-lock.json
  package.json
  yarn.lock
Labels: Chore

#9 Design : Carousel 기본 너비, 높이 수정
  index.html
  src/assets/fake-shop 16x16.png
  src/components/Filter.jsx
  src/components/carousel/Carousel.jsx
  src/views/Accessory.jsx
  src/views/Digital.jsx
  src/views/Fashion.jsx
Labels: Design

#10 Refactor : map 코드 수정
  src/views/MainPage.jsx
Labels: Refactor

#11 !HOTFIX : CORS 에러 해결
  package.json
  src/redux/store.js
  src/views/MainPage.jsx
Labels: bug

#12 Docs : README.md 추가
  README.md
  src/data/CarouselDummy.js
Labels: Chore
